# 1. Named Entity Recognization

In [36]:
import nltk

#nltk.download('maxent_ne_chunker')
#nltk.download('words')

In [37]:
  
paragraph = """The Taj Mahal was built by Emperor Shah Jahan"""
               
               
# POS Tagging
words = nltk.word_tokenize(paragraph)



In [38]:
tagged_words = nltk.pos_tag(words)

In [39]:
# Named entity recognition
namedEnt = nltk.ne_chunk(tagged_words)
namedEnt.draw()

In [40]:
orga = """
ORGANIZATION	Georgia-Pacific Corp., WHO
PERSON	Eddy Bonte, President Obama
LOCATION	Murray River, Mount Everest
DATE	June, 2008-06-29
TIME	two fifty a m, 1:30 p.m.
MONEY	175 million Canadian Dollars, GBP 10.40
PERCENT	twenty pct, 18.75 %
FACILITY	Washington Monument, Stonehenge
GPE	South East Asia, 
"""

In [41]:
words = nltk.word_tokenize(orga)

In [42]:
tagged_words_new = nltk.pos_tag(words)

In [43]:
nameentity = nltk.ne_chunk(tagged_words_new)

In [44]:
nameentity.draw()

# 2. Text Visuatization

Bag of Words

In [45]:
import nltk
import re

paragraph = """Thank you all so very much. Thank you to the Academy. 
               Thank you to all of you in this room. I have to congratulate 
               the other incredible nominees this year. The Revenant was 
               the product of the tireless efforts of an unbelievable cast
               and crew. First off, to my brother in this endeavor, Mr. Tom 
               Hardy. Tom, your talent on screen can only be surpassed by 
               your friendship off screen … thank you for creating a t
               ranscendent cinematic experience. Thank you to everybody at 
               Fox and New Regency … my entire team. I have to thank 
               everyone from the very onset of my career … To my parents; 
               none of this would be possible without you. And to my 
               friends, I love you dearly; you know who you are. And lastly,
               I just want to say this: Making The Revenant was about
               man's relationship to the natural world. A world that we
               collectively felt in 2015 as the hottest year in recorded
               history. Our production needed to move to the southern
               tip of this planet just to be able to find snow. Climate
               change is real, it is happening right now. It is the most
               urgent threat facing our entire species, and we need to work
               collectively together and stop procrastinating. We need to
               support leaders around the world who do not speak for the 
               big polluters, but who speak for all of humanity, for the
               indigenous people of the world, for the billions and 
               billions of underprivileged people out there who would be
               most affected by this. For our children’s children, and 
               for those people out there whose voices have been drowned
               out by the politics of greed. I thank you all for this 
               amazing award tonight. Let us not take this planet for 
               granted. I do not take tonight for granted. Thank you so very much."""
               

 we need BOW model becaues any ml or dl algo only understands numbers or float so the BOWM is a necessaty

In [46]:
data = nltk.sent_tokenize(paragraph)

In [47]:
words = nltk.word_tokenize(paragraph)

In [48]:
len(words)

347

In [49]:
for i in range(len(data)):
    data[i] = data[i].lower()
    #lowercasing the dataset
    data[i] = re.sub(r"\W",' ',data[i])
    # puncuation chars
    data[i] = re.sub(r"\s+",' ',data[i])

In [50]:
data

['thank you all so very much ',
 'thank you to the academy ',
 'thank you to all of you in this room ',
 'i have to congratulate the other incredible nominees this year ',
 'the revenant was the product of the tireless efforts of an unbelievable cast and crew ',
 'first off to my brother in this endeavor mr tom hardy ',
 'tom your talent on screen can only be surpassed by your friendship off screen thank you for creating a t ranscendent cinematic experience ',
 'thank you to everybody at fox and new regency my entire team ',
 'i have to thank everyone from the very onset of my career to my parents none of this would be possible without you ',
 'and to my friends i love you dearly you know who you are ',
 'and lastly i just want to say this making the revenant was about man s relationship to the natural world ',
 'a world that we collectively felt in 2015 as the hottest year in recorded history ',
 'our production needed to move to the southern tip of this planet just to be able to find

In [51]:
#Creating The histogram

In [52]:
#per line tokenizing
word2count = {}
for datas in data:
    words = nltk.word_tokenize(datas)
    for word in words:
        if word not in word2count.keys():
            word2count[word] = 1
            #jodi na thake tale atleast 
            #it has apppeared once
            
        else:
            word2count[word] += 1
            #jodi thake tale count barachi            

In [53]:
word2count

{'thank': 8,
 'you': 12,
 'all': 4,
 'so': 2,
 'very': 3,
 'much': 2,
 'to': 16,
 'the': 17,
 'academy': 1,
 'of': 10,
 'in': 4,
 'this': 9,
 'room': 1,
 'i': 6,
 'have': 3,
 'congratulate': 1,
 'other': 1,
 'incredible': 1,
 'nominees': 1,
 'year': 2,
 'revenant': 2,
 'was': 2,
 'product': 1,
 'tireless': 1,
 'efforts': 1,
 'an': 1,
 'unbelievable': 1,
 'cast': 1,
 'and': 8,
 'crew': 1,
 'first': 1,
 'off': 2,
 'my': 5,
 'brother': 1,
 'endeavor': 1,
 'mr': 1,
 'tom': 2,
 'hardy': 1,
 'your': 2,
 'talent': 1,
 'on': 1,
 'screen': 2,
 'can': 1,
 'only': 1,
 'be': 4,
 'surpassed': 1,
 'by': 3,
 'friendship': 1,
 'for': 10,
 'creating': 1,
 'a': 2,
 't': 1,
 'ranscendent': 1,
 'cinematic': 1,
 'experience': 1,
 'everybody': 1,
 'at': 1,
 'fox': 1,
 'new': 1,
 'regency': 1,
 'entire': 2,
 'team': 1,
 'everyone': 1,
 'from': 1,
 'onset': 1,
 'career': 1,
 'parents': 1,
 'none': 1,
 'would': 2,
 'possible': 1,
 'without': 1,
 'friends': 1,
 'love': 1,
 'dearly': 1,
 'know': 1,
 'who': 4,
 '

In [54]:
len(word2count)

157

In [55]:
import heapq
# used to find the N most frequent words in the dict

In [56]:

freq_words = heapq.nlargest(100, 
                          word2count, 
                          key=word2count.get)

In [57]:
freq_words

['the',
 'to',
 'you',
 'of',
 'for',
 'this',
 'thank',
 'and',
 'i',
 'my',
 'all',
 'in',
 'be',
 'who',
 'world',
 'very',
 'have',
 'by',
 'we',
 'our',
 'is',
 'not',
 'people',
 'out',
 'so',
 'much',
 'year',
 'revenant',
 'was',
 'off',
 'tom',
 'your',
 'screen',
 'a',
 'entire',
 'would',
 'just',
 's',
 'collectively',
 'planet',
 'it',
 'most',
 'need',
 'do',
 'speak',
 'billions',
 'there',
 'children',
 'tonight',
 'take',
 'granted',
 'academy',
 'room',
 'congratulate',
 'other',
 'incredible',
 'nominees',
 'product',
 'tireless',
 'efforts',
 'an',
 'unbelievable',
 'cast',
 'crew',
 'first',
 'brother',
 'endeavor',
 'mr',
 'hardy',
 'talent',
 'on',
 'can',
 'only',
 'surpassed',
 'friendship',
 'creating',
 't',
 'ranscendent',
 'cinematic',
 'experience',
 'everybody',
 'at',
 'fox',
 'new',
 'regency',
 'team',
 'everyone',
 'from',
 'onset',
 'career',
 'parents',
 'none',
 'possible',
 'without',
 'friends',
 'love',
 'dearly',
 'know',
 'are',
 'lastly']

In [58]:
#Creating the BOG model

X = [] # it will contain the BOW model

# in a BOw each words is a vector 1 - apppears & 0- not appears
for datas in data:
    vector = []
    for word in freq_words:
        if word in nltk.word_tokenize(datas):
            vector.append(1)
        else:
            vector.append(0)
    X.append(vector)

In [59]:
len(data)

21

In [60]:
import numpy as np
np.array(X)

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [61]:
np.array(X).shape

(21, 100)

In [62]:
X = np.asarray(X)
X

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

# Text modelling using TF - IDF Model

In [14]:
import nltk
import re
import heapq
import numpy as np

In [15]:
paragraph = """Thank you all so very much. Thank you to the Academy. 
               Thank you to all of you in this room. I have to congratulate 
               the other incredible nominees this year. The Revenant was 
               the product of the tireless efforts of an unbelievable cast
               and crew. First off, to my brother in this endeavor, Mr. Tom 
               Hardy. Tom, your talent on screen can only be surpassed by 
               your friendship off screen … thank you for creating a t
               ranscendent cinematic experience. Thank you to everybody at 
               Fox and New Regency … my entire team. I have to thank 
               everyone from the very onset of my career … To my parents; 
               none of this would be possible without you. And to my 
               friends, I love you dearly; you know who you are. And lastly,
               I just want to say this: Making The Revenant was about
               man's relationship to the natural world. A world that we
               collectively felt in 2015 as the hottest year in recorded
               history. Our production needed to move to the southern
               tip of this planet just to be able to find snow. Climate
               change is real, it is happening right now. It is the most
               urgent threat facing our entire species, and we need to work
               collectively together and stop procrastinating. We need to
               support leaders around the world who do not speak for the 
               big polluters, but who speak for all of humanity, for the
               indigenous people of the world, for the billions and 
               billions of underprivileged people out there who would be
               most affected by this. For our children’s children, and 
               for those people out there whose voices have been drowned
               out by the politics of greed. I thank you all for this 
               amazing award tonight. Let us not take this planet for 
               granted. I do not take tonight for granted. Thank you so very much."""


In [16]:
# Tokenize sentences
dataset = nltk.sent_tokenize(paragraph)
for i in range(len(dataset)):
    dataset[i] = dataset[i].lower()
    dataset[i] = re.sub(r'\W',' ',dataset[i])
    dataset[i] = re.sub(r'\s+',' ',dataset[i])

In [17]:
#per line tokenizing
# Creating word histogram
word2count = {}
for data in dataset:
    words = nltk.word_tokenize(data)
    for word in words:
        if word not in word2count.keys():
            word2count[word] = 1
            #jodi na thake tale atleast 
            #it has apppeared once
        else:
            word2count[word] += 1
            #jodi thake tale count barachi  

In [18]:
# Selecting best 100 features
freq_words = heapq.nlargest(100,
                            word2count,
                            key=word2count.get)

In [ ]:
#Creating the BOG model

X = [] # it will contain the BOW model

# in a BOw each words is a vector 1 - apppears & 0- not appears
for datas in data:
    vector = []
    for word in freq_words:
        if word in nltk.word_tokenize(datas):
            vector.append(1)
        else:
            vector.append(0)
    X.append(vector)

In [ ]:
X = np.asarray(X)
X

In [19]:
# IDF Dictionary

word_idfs = {}
for word in freq_words:
    doc_count = 0
    for data in dataset:
        if word in nltk.word_tokenize(data):
            doc_count += 1
    word_idfs[word] = np.log(len(dataset)/(1+doc_count))
    # +1 is kindof like a bias

In [20]:
len(word_idfs)

100

In [21]:
# TF Matrix
tf_matrix = {}
for word in freq_words:
    doc_tf = []
    for data in dataset:
        frequency = 0
        for w in nltk.word_tokenize(data):
            if word == w:
                frequency += 1
        tf_word = frequency/len(nltk.word_tokenize(data))
        doc_tf.append(tf_word)
    tf_matrix[word] = doc_tf   

In [25]:
# TF - IDF Calculation
tfidf_matrix  = []
for word in tf_matrix.keys():
    tfidf = []
    for value in tf_matrix[word]:
        score = value * word_idfs[word]
        tfidf.append(score)
    tfidf_matrix.append(tfidf)  

In [33]:
X = np.asarray(tfidf_matrix).astype('float64')
X

array([[0.        , 0.12932543, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.11192316, 0.06217953, ..., 0.        , 0.        ,
        0.        ],
       [0.12365622, 0.14838747, 0.16487497, ..., 0.        , 0.        ,
        0.14838747],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [34]:
X.shape

(100, 21)

In [35]:
X = X.T
X.shape

(21, 100)